### ISSUE TITLE
extend_Name_Binding_Time Throws on Overpay

### ISSUE THREAD

**Issue by RobertMCForster** [EthereumCommonwealth/DexNS#2] opened 2017-11-28 02:55 UTC
Because "DexNS commission" is sent msg.value in this function on the frontend contract instead of "namePrice" (like in the register function), the contract will not have the funds to return any overpayment to the sender and will throw.

**Comment by Dexaran** [comment] 2017-11-29 22:43
Confirmed. Fixed with https://github.com/EthereumCommonwealth/DexNS/commit/95099bed1dc335a24e0488cbfd217da7760cbfab

**Comment by Dexaran** [comment] 2017-11-29 22:48
This bug was evaluated as point 3 of the bug bounty: **code flaws that can not violate contract workflow** because it cannot violate contract workflow or make any harm to contract users. Any overpay will be reverted and any normal `extend_Name_Binding_Time` will be successfully executed.

I'm ready to reward you with $250 in ETC or any other crypto that I can buy if you don't like ETC. I'd like to evaluate the reward at Nov 30, 2017 23:00 CEST by Poloniex ETCUSDT rate and then I will send it to `0x490be2bd4d8c7bdef4f8136b9c6a6f6d0c8a0477` address.

**Comment by RobertMCForster** [comment] 2017-11-29 23:37
Great, sounds good.

**Comment by Dexaran** [comment] 2017-11-30 21:10
Sent: https://gastracker.io/tx/0xcd2891d567f20bbed56b1051129877ba5d3533b51729d81f08b0030252b0fbf5

**Closed as completed** 2017-12-11 17:48 UTC
Labels: bugbounty: confirmed, paid
